### ISSUE TITLE
Similar Project on SourceForge

### ISSUE THREAD

**Issue by innesst** [Anc813/MicMute#3]
https://sourceforge.net/projects/micmute/

**Comment by trono6** [comment]
it's a couple of years I use the original micmute from Sourceforge, is this a copy or is it based on the original trying to improve it since is not updated anymore? or maybe devs are the same person..

on the readme I didn't see mentioned the Sourceforge project but the similarities are a bit suspicious

**Comment by Anc813** [comment]
@innesst @trono6 it's a new project written in c#.
I never used micmute from sourceforge.

**Comment by dwettstein** [comment]
This issue could be closed. 😇
